name: Build

on:
    push:
        branches: [main]

    workflow_dispatch:

jobs:
    assem-release:
        runs-on: ubuntu-latest
        container: reactnativecommunity/react-native-android
        steps:
            - uses: actions/checkout@v2

            - name: Install yarn dependencies
              run: yarn install

            - name: License report
              run: yarn --silent license-report --package=./package.json --output=json > ./src/utils/openSourceLibraries.json

            - name: Init readhubnBuild
              run: yarn json -I -f package.json -e "this.readhubnBuild=${GITHUB_RUN_NUMBER}"

            - name: Build application
              run: cd android && chmod +x gradlew && ./gradlew assembleRelease

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: app-release
                  path: android/app/build/outputs/apk/release
